gTile/gTile

- extension.js
As described at https://github.com/micheleg/dash-to-dock/pull/770, all workspace related features that used to be on **global.screen** have moved to **global.workspace_manager**.
The fix enables gTile to work on all GNOME <= 3.30.
NOTE: That the diff shows a bunch of changes but most of it was white-space removed by my linter.
> Fix gTile for GNOME >= 3.30

- metadata.json
I figured this was missing when looking at #51
> Adds 3.30 to supported gnome-shell versions

- README.md
- extension.js
- prefs.js
It took some time until I figured out how the presets are defined. I understood the hint "Resize presets (grid size and 2 corners, 2x2 0:1 0:1 is left bottom quarter)" as a rectangle that spans on a grid of coordinates. But that's not how it works. It spans from one tile to another. A colleague fell to the same assumption :-).
I therefore tried to clarify this a bit.
> Enhance description regarding preset definitions.

- README.md
As #59 shows that some additional explanation is needed.
Did my best to make the alpha heavy, mostly white icons visible on white github's background.
> Describing what the animation toggle and auto-close toggle buttons do

- prefs.js
In the settings dialogue, some labels could be cut off and the window had to be resized. I changed the labels to allow word-wrap.
> allow wrapping of labels in settings dialogue

- prefs.js
Attach new signal "accel-cleared" and use it to disable the associated
accelerator. It uses the standard Gnome UX: select accelerator, click/enter, then backspace to disable.
Demo:
> Add feature to disable accelerators (fixes #38)

- prefs.js
Vi-style actions are indistinguishable in the UI.
> Clarify vi-style pretty_names, and correct spelling error

- BUILD.bazel
- app.ts
- hotkeys.ts
- prefs.js
- snaptoneighbors.ts
My previous commit broke the extension because of unresolved references to logging.js. This change converts hotkeys.js and snaptoneighbors.js to Typescript, which makes importing them safer.
> Fix bad imports of logging.js; migrate more files to Typescript.

- app.ts
Tweener is removed in the upcomming gnome 3.38. `Clutter.Actor.prototype.ease()` can be used as a drop in replacement.
Reference: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1200
https://github.com/andyholmes/gnome-shell-extension-gsconnect/commit/acf0aa36fa3ab1ed7577a3277352d1963160fbde
Tested on Fedora 33 running Gnome 3.37.90 pre-release.
> app: Replace use of tweener with clutter

- app.ts
When `destroyGrids` function call fails the laucher is not correctly destroyead what leads to GTileStatusButton still registered in the StatusArea. It is impossible then to reload the plugin as the environment complains with the following error `JS ERROR: Extension gTile@vibou: Error: Extension point conflict: there is already a status indicator for role GTileStatusButton`. Following PR moves the `destroyGrids` function call after the launcher.destroy() call.
> Move destroy grids call after launcher destroy is called

- app.ts
Resolves to: https://github.com/gTile/gTile/issues/176#issue-751198339
After a recent update, I noticed that all of my windows would properly resize, except gnome-terminal.
gnome-terminal would resize properly, but not move.
Examining the logs for gTile, the coordinates looked correct. After experimenting in Looking Glass for a bit it, I found that when following this same flow, (get windows from active_workspace, iterate to find the has_focus, and move_resize_frame), the window would resize but wouldn't always move. However, running move_frame, before or after always worked.
I added this change locally, restarted my session, and it fixed the issue with gnome-shell.
I'm running:
Debian 5.9.1-1kali2
GNOME Shell 3.38.1
gtk-launch --version: 3.24.23
version number:    11.0
X.Org version: …
> Update app.ts, move_frame before move_resize_frame

- app.ts
- gnometypes.ts
_getInvisibleBorderPadding@/home/red/.local/share/gnome-shell/extensions/gTile@vibou/extension.j\
s:1352:21
moveResizeWindowWithMargins@/home/red/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1382:30
AutoTileNCols@/home/red/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:2036:5
key_bindings_tiling<@/home/red/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:826:28
Change also includes minor type safety improvements.
> Fix minor null object JS ERROR from log, other minor refactoring.

- app.ts
Using the global delegate seems to lead to double subscription to `resize-done`, which gradually slows down global shortcuts, i.g. global contract or expand windows. Creating a new delegate each time, as it was in V42, seems to solve that issue.
Please see more details in [Gradually slowing down while using global expand and contract edges](https://github.com/gTile/gTile/issues/212)
> Attempt to fix bug #212

- metadata.json
Currently the extension is marked not compatible with 40.1 on https://extensions.gnome.org/.
Changing the version from 40.0 to 40 appears to fix this and allows it to load on and updated Fedora 34.
This seems to be a common pattern, for example:
https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/metadata.json#L7
Which does "work" in Gnome 40.1
> Change shell-version metadata to be 40

- schemas/org.gnome.shell.extensions.gtile.gschema.xml
Super + Control <8, 5, 2> should fill entire screen using 2x3 grid
See the neighboring `resize11` through `resize19` lines which all use `2x3`.
There's another note about this typo in https://github.com/gTile/gTile/pull/5/files#r146127144
> Fixup for consistent 2x3 scheme defaults

- metadata.json
GNOME 41 beta has been released and is in Fedora 35 pre-releases. As near as I can tell, it operates properly with no changes other than the metadata.
Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>
> Add support for GNOME 41

- README.md
- app.ts
- prefs.js
- tilespec.ts
Follow up of https://github.com/gTile/gTile/pull/266
This fixes window margins issue when new absolute coordinates are used in the presets. E.g. `0.0:0.0 1.0 1.0` previously applied window margins, with or without "Apply margin to fullscreen windows" enabled. This effectively fixes the bug.
Also adds descriptions to README about the new syntax.
> Fix window margins for fullscreen windows when new coordinates are used and amend README

- metadata.json
I'm not familiar with gnome (in terms of  API chagnes between 42 and 41), netither the stack used in this repo, but the change I made here works in my PC.
Resolves #281
> Gnome 42 support

- stylesheet.css
This PR fixes issues with UI on gnome-shell with Default, Minimal Dark and Minimal Light themes on 2k-4k monitors
@ref https://github.com/gTile/gTile/issues/60
@ref https://github.com/gTile/gTile/issues/261
How it was:
This PR makes this:
> Fix default, minimal dark and minimal light themes

- metadata.json
I've tested this change in my Fedora rawhide with Gnome 43 and it runs without apparent issues.
> metadata.json: Support for Gnome 43

- CHANGELOG.md
- README.md
- dist/metadata.json
- src/core/App.ts
- src/core/DesktopManager.ts
- src/core/HotkeyManager.ts
- src/core/OverlayManager.ts
- src/extension.ts
- src/prefs.ts
- src/types/desktop.ts
- src/types/settings.ts
- src/ui/Overlay.ts
- src/ui/PanelButton.ts
- src/ui/Preview.ts
- src/ui/overlay/ButtonBar.ts
- src/ui/overlay/Container.ts
- src/ui/overlay/Grid.ts
- src/ui/overlay/IconButton.ts
- src/ui/overlay/TextButton.ts
- src/ui/overlay/TitleBar.ts
- src/util/gc.ts
- src/util/volatile.ts
The latest version of gTile was rejected from being published on gnome.extensions.org.
See https://extensions.gnome.org/review/48580
This PR addresses the points raised by @jrahmatzadeh. I would appreciate if you could directly review to this PR, so we can skip unnecessary review-loops on EGO.
> 1. Don't use version when importing.
I am [still not convinced](https://github.com/oae/gnome-shell-pano/pull/222#issuecomment-1812880830) how this helps with type-safe development. But I gather from your [comment](https://github.com/oae/gnome-shell-pano/pull/222#issuecomment-1814075558) that you specifically refer to versioned imports that are also a direct dependency to `gnome-shell`. This only concerns the `Gio` and `Gtk` imports in this project. I've removed the version constrain from all of …
> Compatibility for gnome.extensions.org

- README.md
Updated a couple small typos. Also noticed the main video demoing the autotile feature was unable to play in Firefox, VLC, Gnome Video (all Rocky 9) nor on Safari (iOS 13). MPV and Handbrake were able to read the file but attached a version I re-encoded with Handbrake which seems to work well for all the above.
https://github.com/gTile/gTile/assets/3069222/afe8ccbb-2035-4c6f-a466-120eb98316c9
> Correct a couple typos.

- README.md
This one got me scratching my head for a couple minutes.
> Fix typo in GridSpec example

- dist/schemas/org.gnome.shell.extensions.gtile.gschema.xml
The "contract-down" action moves the bottom window edge upwards. Correct the key's summary by changing it from "Contract top window edge upwards" to "Contract bottom window edge upwards".
> Fix typo in "contract-down" setting description
